dmr--ToolboxProxy[idle="false"] * {
    background: transparent;
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0.00000 transparent,           stop:0.06666 transparent,
        stop:0.06667 rgba(16, 16, 16, 0.8), stop:1.00000 rgba(16, 16, 16, 0.8)
    );
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
} 

dmr--ToolboxProxy[idle="true"] * {
    background: rgba(16, 16, 16, 0.6);
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
}

dmr--ToolboxProxy[idle="false"] Dtk--Widget--DImageButton,
dmr--ToolboxProxy[idle="false"] QLabel {
    background: transparent;
}

dmr--ToolboxProxy[idle="true"] Dtk--Widget--DImageButton,
dmr--ToolboxProxy[idle="true"] QLabel {
    background: transparent;
}

#ToolBoxTopBorder {
    background: transparent;
    border-bottom: 1px inset rgba(0, 0, 0, 0.5);
}

#ToolBoxTopBorderInner {
    background: transparent;
    border-bottom: 1px inset rgba(0, 0, 0, 0.03);
}

Dtk--Widget--DImageButton#ListBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/list-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/list-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/list-press.svg);
}

Dtk--Widget--DImageButton#SubtitleBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/Subtitle-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/Subtitle-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/Subtitle-press.svg);
}

Dtk--Widget--DImageButton#PrevBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/previous-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/previous-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/previous-press.svg);
}

Dtk--Widget--DImageButton#NextBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/next-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/next-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/next-press.svg);
}

Dtk--Widget--DImageButton#PlayBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/play-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/play-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/play-press.svg);
}

Dtk--Widget--DImageButton#PauseBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/pause-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/pause-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/pause-press.svg);
}

Dtk--Widget--DImageButton#FsBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/fullscreen-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/fullscreen-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/fullscreen-press.svg);
}

Dtk--Widget--DImageButton#UnfsBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/exit-fullscreen-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/exit-fullscreen-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/exit-fullscreen-press.svg);
}

dmr--VolumeButton#VolHigh {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-high-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-high-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-high-press.svg);
}

dmr--VolumeButton#VolMid {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-medium-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-medium-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-medium-press.svg);
}


dmr--VolumeButton#VolLow {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-low-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-low-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-low-press.svg);
}

dmr--VolumeButton#VolOff {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-off-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-off-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-off-press.svg);
}

dmr--VolumeButton#VolMute {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-hover.svg);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-press.svg);
}

#MovieProgress {
    background: transparent;
}

#MovieProgress::groove:horizontal {
    background: transparent;
    position: absolute;
    left: 0px; right: 0px;
}
#MovieProgress::handle:horizontal {
    background:transparent;
    margin: 5px -5px;
}
#MovieProgress::add-page:horizontal {
    background: transparent;
}
#MovieProgress::sub-page:horizontal {
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0.00000  transparent,          stop:0.33333 transparent,
        stop:0.33334  #2eacff,              stop:0.50000 #2eacff,
        stop:0.50001  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)
    );
}

