dmr--ToolboxProxy, dmr--ToolboxProxy * {
    background-color: rgba(23, 23, 23, 0.92);
}

QLabel, Dtk--Widget--DImageButton {
    background: transparent;
}

#ToolBoxTopBorder {
    background-color: rgba(0, 0, 0, 0.5);
}

#ToolBoxTopBorderInner {
    background: transparent;
    border-bottom: 1px inset rgba(255, 255, 255, 0.05);
}

Dtk--Widget--DImageButton#ListBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/list-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/list-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/list-press.png);
}

Dtk--Widget--DImageButton#SubtitleBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/Subtitle-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/Subtitle-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/Subtitle-press.png);
}

Dtk--Widget--DImageButton#PrevBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/previous-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/previous-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/previous-press.png);
}

Dtk--Widget--DImageButton#NextBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/next-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/next-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/next-press.png);
}

Dtk--Widget--DImageButton#PlayBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/play-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/play-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/play-press.png);
}

Dtk--Widget--DImageButton#PauseBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/pause-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/pause-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/pause-press.png);
}

Dtk--Widget--DImageButton#FsBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/fullscreen-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/fullscreen-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/fullscreen-press.png);
}

Dtk--Widget--DImageButton#UnfsBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/exit-fullscreen-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/exit-fullscreen-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/exit-fullscreen-press.png);
}

dmr--VolumeButton#VolHigh {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-high-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-high-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-high-press.png);
}

dmr--VolumeButton#VolMid {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-medium-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-medium-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-medium-press.png);
}


dmr--VolumeButton#VolLow {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-low-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-low-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-low-press.png);
}

dmr--VolumeButton#VolOff {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-off-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-off-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-off-press.png);
}

dmr--VolumeButton#VolMute {
    qproperty-normalPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/audio-volume-muted-blocked-panel-press.png);
}

#MovieProgress {
    background: transparent;
}

#MovieProgress::groove:horizontal {
    background: transparent;
    position: absolute;
    left: 0px; right: 0px;
}
#MovieProgress::handle:horizontal {
    background:transparent;
    margin: 5px -5px;
}
#MovieProgress::add-page:horizontal {
    background: transparent;
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0        transparent,                  stop:0.08333 transparent,
        stop:0.08400  rgba(255, 255, 255, 0.08),    stop:0.16666 rgba(255, 255, 255, 0.08),
        stop:0.17000  rgba(0, 0, 0, 0.0),           stop:0.24999 rgba(0, 0, 0, 0.0),
        stop:0.25000  rgba(0, 0, 0, 0.0),           stop:1 rgba(0, 0, 0, 0.0)
    );
}
#MovieProgress::sub-page:horizontal {
    background: #2ca7f8;
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0        #2eacff,              stop:0.08333 #2eacff,
        stop:0.08333  #2eacff,              stop:0.16666 #2eacff,
        stop:0.17000  rgba(0, 0, 0, 0.3),   stop:0.24999 rgba(0, 0, 0, 0.3),
        stop:0.25000  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)
    );
}


