dmr--MainWindow {
    background-color: rgb(16, 16, 16);
}

Dtk--Widget--DTitlebar, Dtk--Widget--DTitlebar * {
    background-color: #171717;
}

/* ---------- Mini Mode ----------------------------- */

Dtk--Widget--DImageButton#MiniPlayBtn {
    qproperty-normalPic: url(:/resources/icons/dark/mini/play-normal-mini.png);
    qproperty-hoverPic: url(:/resources/icons/dark/mini/play-hover-mini.png);
    qproperty-pressPic: url(:/resources/icons/dark/mini/play-press-mini.png);
}

Dtk--Widget--DImageButton#MiniPauseBtn {
    qproperty-normalPic: url(:/resources/icons/dark/mini/pause-normal-mini.png);
    qproperty-hoverPic: url(:/resources/icons/dark/mini/pause-hover-mini.png);
    qproperty-pressPic: url(:/resources/icons/dark/mini/pause-press-mini.png);
}

Dtk--Widget--DImageButton#MiniQuitMiniBtn {
    qproperty-normalPic: url(:/resources/icons/dark/mini/restore-normal-mini.png);
    qproperty-hoverPic: url(:/resources/icons/dark/mini/restore-hover-mini.png);
    qproperty-pressPic: url(:/resources/icons/dark/mini/restore-press-mini.png);
}

Dtk--Widget--DImageButton#MiniCloseBtn {
    qproperty-normalPic: url(:/resources/icons/dark/normal/close-normal.png);
    qproperty-hoverPic: url(:/resources/icons/dark/normal/close-hover.png);
    qproperty-pressPic: url(:/resources/icons/dark/normal/close-press.png);
}



