dmr--ToolboxProxy, dmr--ToolboxProxy * {
/*
    background: transparent;
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0.00000 transparent,               stop:0.16666 transparent,
        stop:0.16667 rgba(252, 252, 252, 0.88), stop:1.00000 rgba(252, 252, 252, 0.88)
    );
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    */
    background: transparent;
    border: 1px solid rgba(0,0,0,0.04);
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.10);
    border-radius: 18px;
    border-radius: 18px;
}

QLabel, Dtk--Widget--DImageButton {
    background: transparent;
}


Dtk--Widget--DImageButton#ListBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/list-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/list-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/list-press.svg);
}

Dtk--Widget--DImageButton#SubtitleBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/Subtitle-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/Subtitle-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/Subtitle-press.svg);
}

Dtk--Widget--DImageButton#PrevBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/previous-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/previous-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/previous-press.svg);
}

Dtk--Widget--DImageButton#NextBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/next-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/next-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/next-press.svg);
}

Dtk--Widget--DImageButton#PlayBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/play-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/play-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/play-press.svg);
}

Dtk--Widget--DImageButton#PauseBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/pause-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/pause-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/pause-press.svg);
}

Dtk--Widget--DImageButton#FsBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/fullscreen-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/fullscreen-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/fullscreen-press.svg);
}

Dtk--Widget--DImageButton#UnfsBtn {
    qproperty-normalPic: url(:/resources/icons/light/normal/exit-fullscreen-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/exit-fullscreen-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/exit-fullscreen-press.svg);
}

dmr--VolumeButton#VolHigh {
    qproperty-normalPic: url(:/resources/icons/light/normal/audio-volume-high-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/audio-volume-high-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/audio-volume-high-press.svg);
}

dmr--VolumeButton#VolMid {
    qproperty-normalPic: url(:/resources/icons/light/normal/audio-volume-medium-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/audio-volume-medium-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/audio-volume-medium-press.svg);
}


dmr--VolumeButton#VolLow {
    qproperty-normalPic: url(:/resources/icons/light/normal/audio-volume-low-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/audio-volume-low-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/audio-volume-low-press.svg);
}

dmr--VolumeButton#VolOff {
    qproperty-normalPic: url(:/resources/icons/light/normal/audio-volume-off-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/audio-volume-off-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/audio-volume-off-press.svg);
}

dmr--VolumeButton#VolMute {
    qproperty-normalPic: url(:/resources/icons/light/normal/audio-volume-muted-blocked-panel-normal.svg);
    qproperty-hoverPic: url(:/resources/icons/light/normal/audio-volume-muted-blocked-panel-hover.svg);
    qproperty-pressPic: url(:/resources/icons/light/normal/audio-volume-muted-blocked-panel-press.svg);
}

#MovieProgress {
    background: transparent;
}

/* simulate dynamic expanding of tool proxy background */
/*#MovieProgress[Hover="true"]::groove:horizontal {*/
    /*background: transparent;*/
    /*background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,*/
        /*stop:0.00000  transparent,          stop:0.33333 transparent,*/
        /*stop:0.33334  rgba(252, 252, 252, 0.88),  stop:0.50000 rgba(252, 252, 252, 0.88),*/
        /*stop:0.50001  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)*/
    /*);*/
    /*position: absolute;*/
    /*left: 0px; right: 0px;*/
/*}*/
#MovieProgress[Hover="false"]::groove:horizontal {
    background: transparent;
    position: absolute;
    left: 0px; right: 0px;
}

#MovieProgress::handle:horizontal {
    background:transparent;
    margin: 5px -5px;
}


/*#MovieProgress[Hover="true"]::add-page:horizontal {*/
    /*background: transparent;*/
    /*background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,*/
        /*stop:0.00000  transparent,          stop:0.33333 transparent,*/
        /*stop:0.33334  rgba(0, 0, 0, 0.1),   stop:0.37500 rgba(0, 0, 0, 0.1),*/
        /*stop:0.37501  rgba(255, 255, 255, 0.08),  stop:0.41666 rgba(255, 255, 255, 0.08),*/
        /*stop:0.41667  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)*/
    /*);*/
/*}*/

/*#MovieProgress[Hover="true"]::sub-page:horizontal {*/
    /*background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,*/
        /*stop:0.00000  transparent,          stop:0.33333 transparent,*/
        /*stop:0.33334  #2eacff,              stop:0.58333 #2eacff,*/
        /*stop:0.58334  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)*/
    /*);*/
/*}*/

#MovieProgress[Hover="false"]::add-page:horizontal {
    background: transparent;
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0.00000  transparent,          stop:0.50000 transparent,
        stop:0.50001  rgba(0, 0, 0, 0.1),   stop:0.54166 rgba(0, 0, 0, 0.1),
        stop:0.54167  rgba(255, 255, 255, 0.08),  stop:0.58333 rgba(255, 255, 255, 0.08),
        stop:0.58334  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)
    );
}
#MovieProgress[Hover="false"]::sub-page:horizontal {
    background-color: qlineargradient(x1:0 y1:0, x2:0 y2:1,
        stop:0.00000  transparent,          stop:0.50000 transparent,
        stop:0.50001  #2eacff,              stop:0.58333 #2eacff,
        stop:0.58334  rgba(0, 0, 0, 0.0), stop:1 rgba(0, 0, 0, 0.0)
    );
}

